---
- name: "Create Group Admin"
  ansible.builtin.group:
    name: "admin"
    state: present
  no_log: true

- name: "Create Admin User Accounts"
  ansible.builtin.user:
    name: "{{ admin_user.name }}"
    password: "{{ admin_user.password | password_hash('sha512') }}"
    groups: "admin"
  loop: "{{ users_admin }}"
  loop_control:
    loop_var: admin_user
  no_log: true

- name: "Add Authorized Keys"
  ansible.builtin.authorized_key:
    user: "{{ admin_user.name }}"
    key: "{{ lookup('file', 'files/' + admin_user.name + '.key.pub') }}"
  loop: "{{ users_admin }}"
  loop_control:
    loop_var: admin_user
#    - "{{ users_no_admin }}"
  no_log: true

- name: "Allow Admin Users to Sudo Without a Password"
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^%sudo"
    line: "%admin ALL=(ALL) NOPASSWD: ALL"
  no_log: true

## Mettre plus tard dans un fichier de gestionnaire (handlers)
# - name: "Disable Pi User"
#   ansible.builtin.command:
#     cmd: usermod -L pi
