- name: Créer le répertoire de wordpress 
  file:
    path: /var/wp
    state: directory
    mode: '0750'
    owner: pi
    group: users

- name: Copier le fichier docker-compose.yml
  copy:
    src: wordpress_docker-compose.yml
    dest: /tmp/


- name: Exécuter docker-compose up -d de Wordpress
  command: docker-compose -f /tmp/wordpress_docker-compose.yml up -d