- name: Disabling HDMI Port
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^#?hdmi=.*'
    line: 'hdmi=0'
    state: present
  become: true

- name: Disabling audio on the jack port
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^#?dtparam=audio=.*'
    line: 'dtparam=audio=off'
    state: present
  become: true

- name: Force boot to console mode (without graphical interface)
  ansible.builtin.file:
    src: /lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link
  become: true
  tags: disable_hdmi

- name: Disable console autologin (remove autologin.conf)
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    state: absent
  become: true
  tags: disable_hdmi
