---
- name: Ensure ufw is installed.
  apt:
    name: ufw
    state: present

- name: Set ufw policy
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: Enabling ufw logging
  ufw:
    logging: on

- name: Enable and rate limit ssh port
  ufw:
    rule: limit
    port: '{{ ssh_port | default(22) }}'
    proto: tcp