- name: Mettre à jour les listes de paquets
  apt:
    update_cache: yes

- name: Installer les paquets nécessaires
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Ajouter le dépôt Docker
  shell: |
    apt-get install ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/raspbian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

- name: Ajouter le dépôt Docker
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/raspbian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Remettre à jour les listes de paquets
  apt:
    update_cache: yes

- name: Installer Docker Engine
  apt:
    name:
      - docker
      - docker-clean
      - docker-compose
      - docker-doc
      - docker.io
    state: present

- name: Ajouter l'utilisateur à docker
  user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
  with_items:
    - "{{ users_admin }}"