---
# - name: Check if log2ram is already installed
#   stat:
#     path: /etc/systemd/system/log2ram.service
#   register: log2ram_installed

# - name: 'Skip if already installed' NE FONCTIONNE PAS
#   fail:
#   when: log2ram_installed.stat.exists

- name: Download log2ram services from master branch
  ansible.builtin.get_url:
    url: "https://github.com/azlux/log2ram/archive/master.tar.gz"
    dest: "/tmp/log2ram.tar.gz"
    mode: '0755'

- name: Extract archive
  ansible.builtin.unarchive:
    src: /tmp/log2ram.tar.gz
    dest: /tmp/
    remote_src: true

- name: Create /usr/local/bin/ directory if it does not exist
  ansible.builtin.file:
    path: /usr/local/bin/
    state: directory
    mode: '0755'

- name: Log2ram.service
  ansible.builtin.copy:
    src: /tmp/log2ram-master/log2ram.service
    dest: /etc/systemd/system/log2ram.service
    mode: '0644'
    remote_src: true

- name: Log2ram-daily.service
  ansible.builtin.copy:
    src: /tmp/log2ram-master/log2ram-daily.service
    dest: /etc/systemd/system/log2ram-daily.service
    mode: '0644'
    remote_src: true

- name: Log2ram-daily.timer
  ansible.builtin.copy:
    src: /tmp/log2ram-master/log2ram-daily.timer
    dest: /etc/systemd/system/log2ram-daily.timer
    mode: '0644'
    remote_src: true

- name: Log2ram.logrotate
  ansible.builtin.copy:
    src: /tmp/log2ram-master/log2ram.logrotate
    dest: /etc/logrotate.d/log2ram
    mode: '0644'
    remote_src: true

- name: Log2ram binary
  ansible.builtin.copy:
    src: /tmp/log2ram-master/log2ram
    dest: /usr/local/bin/log2ram
    mode: '0755'
    remote_src: true

- name: Log2ram uninstall.sh
  ansible.builtin.copy:
    src: /tmp/log2ram-master/uninstall.sh
    dest: /usr/local/bin/uninstall.sh_log2ram.sh
    mode: '0644'
    remote_src: true

- name: Log2ram config
  ansible.builtin.copy:
    src: /tmp/log2ram-master/log2ram.conf
    dest: /etc/log2ram.conf
    mode: '0644'
    remote_src: true

- name: Change RAM size of log folder to MB {{ log2ram_size }}
  ansible.builtin.lineinfile:
    path: /etc/log2ram.conf
    regexp: '^SIZE='
    line: 'SIZE={{ raspberry_pi_log2ram_size }}M'

- name: Log2ram.service
  ansible.builtin.copy:
    src: /tmp/log2ram-master/uninstall.sh
    dest: /usr/local/bin/uninstall-log2ram.sh
    mode: '0644'
    remote_src: true

- name: Ensure log2ram is running on startup
  ansible.builtin.systemd:
    name: log2ram
    daemon_reload: true
    state: started
    enabled: true

- name: Log2ram cron logrotate
  ansible.builtin.copy:
    src: /tmp/log2ram-master/log2ram.logrotate
    dest: /etc/logrotate.d/log2ram
    mode: '0644'
    remote_src: true

- name: Remove a previous log2ram version
  ansible.builtin.file:
    path: /var/log.hdd
    state: absent
