---
# List of tasks to be executed by the role

- name: "Welcome message"
  ansible.builtin.debug:
    msg:
      - "Hello geeks, nous allons configurer une nouvelle installation de Raspberry Pi OS."
      - "Nous allons (entre autre), installer les packages suivants : {{ raspberry_pi_packages }}"

# Loop over task categories
- name: "Include task categories"
  ansible.builtin.include_tasks:
    file: include_task_category.yml
  loop:
    - { category: "intro", tasks: "{{ raspberry_pi_tasks.intro.tasks }}", active: "{{ raspberry_pi_tasks.intro.active }}" }
    - { category: "mandatory", tasks: "{{ raspberry_pi_tasks.mandatory.tasks }}", active: "{{ raspberry_pi_tasks.mandatory.active }}" }
    - { category: "optional", tasks: "{{ raspberry_pi_tasks.optional.tasks }}", active: "{{ raspberry_pi_tasks.optional.active }}" }
    - { category: "experimental", tasks: "{{ raspberry_pi_tasks.experimental.tasks }}", active: "{{ raspberry_pi_tasks.experimental.active }}" }
  loop_control:
    label: "{{ item.category }}"
  when: item.active
