# File: roles/raspberry_pi/tasks/samba.yml
---

- name: Install Samba packages
  ansible.builtin.package:
    name: "{{ raspberry_pi_samba_packages }}"
    state: present
  tags: samba

- name: Samba configuration
  ansible.builtin.template:
    src: "{{ raspberry_pi_samba_configuration_template }}"
    dest: "{{ raspberry_pi_samba_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  tags: samba

- name: Create Samba users if they don't exist yet
  ansible.builtin.shell: >
    set -o nounset -o pipefail -o errexit &&
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  args:
    executable: /bin/bash
  loop: "{{ users_admin }}"
  loop_control:
    loop_var: samba_user
  no_log: true
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"
  tags: samba

- name: Start Samba service(s)
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ raspberry_pi_samba_services }}"
  loop_control:
    loop_var: samba_service
  tags: samba
