---
- name: Set /etc/localtime
  ansible.builtin.copy:
    src: /usr/share/zoneinfo/{{ raspberry_pi_timezone }}
    dest: /etc/localtime
    mode: '0644'
  notify:
    - Restart cron

- name: Set default timezone
  ansible.builtin.copy:
    content: '{{ raspberry_pi_timezone }}\n'
    dest: /etc/timezone
    mode: '0644'
  notify:
    - Restart cron
