---
- name: Set /etc/localtime
  copy:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
  notify:
    - update tzdata
    - restart cron

- name: Set default timezone
  copy:
    content: '{{ timezone }}\n'
    dest: /etc/timezone
  notify:
    - update tzdata
    - restart cron
