---
- name: Restart cron
  ansible.builtin.systemd:
    name: cron
    state: restarted

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Reconfigure locale
  ansible.builtin.command:
    cmd: dpkg-reconfigure locales --frontend noninteractive
    creates: /etc/locale.gen

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 1200

- name: Restart Samba services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ samba_services }}"

- name: Restart log2ram
  ansible.builtin.systemd:
    name: log2ram
    state: restarted
